2014/05/15 01:24:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive'' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php:381
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/generators/model/ModelCode.php(57): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#15 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/certificados/index.php/gii/model
HTTP_REFERER=http://localhost/certificados/index.php/gii/default/index
---
2014/05/15 01:24:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'certificado'' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php:381
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/generators/model/ModelCode.php(57): CModule->__get('db')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model')
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#15 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/certificados/index.php/gii/model
HTTP_REFERER=http://localhost/certificados/index.php/gii/default/index
---
2014/05/15 01:50:28 [error] [exception.CException] exception 'CException' with message 'El alias "application.components.WebUser" es inválido. Asegúrese de que apunta a un archivo PHP y el archivo tiene permisos de lectura.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php:316
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/YiiBase.php(196): YiiBase::import('application.com...', true)
#1 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(386): YiiBase::createComponent(Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CModule.php(103): CModule->getComponent('user')
#3 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/layouts/main.php(35): CModule->__get('user')
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/Applications/X...', Array, true)
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(206): COutputProcessor->run()
#10 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#11 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/views/layouts/column1.php(6): CBaseController->endContent()
#12 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(126): require('/Applications/X...')
#13 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/Applications/X...', Array, true)
#14 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(784): CBaseController->renderFile('/Applications/X...', Array, true)
#15 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/SiteController.php(32): CController->render('index')
#16 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#17 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#18 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#19 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('index')
#21 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#22 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#23 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/certificados/index.php/site/login
HTTP_REFERER=http://localhost/certificados/index.php
---
2014/05/15 01:59:36 [error] [exception.CException] exception 'CException' with message 'SiteController no ha podido encontrar la vista "resetpass" solicitada.' in /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php:878
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(782): CController->renderPartial('resetpass', Array, true)
#1 /Applications/XAMPP/xamppfiles/htdocs/certificados/protected/controllers/SiteController.php(130): CController->render('resetpass', Array)
#2 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionResetPass()
#3 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(282): CController->run('resetpass')
#7 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('site/resetpass')
#8 /Applications/XAMPP/xamppfiles/htdocs/yii/framework/base/CApplication.php(169): CWebApplication->processRequest()
#9 /Applications/XAMPP/xamppfiles/htdocs/certificados/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/certificados/index.php?r=site/resetpass
HTTP_REFERER=http://localhost/certificados/index.php?r=site/login
---
